### ISSUE TITLE
@include-media not working in nested items

### ISSUE THREAD

**Issue by 7iomka** [jackmcpickle/postcss-include-media#645]
We have issues with custom @include-media when we used `postcss-nested` plugin

- This code produce an error:

  ```css
  .nowrapBreakpoint_md {
    @include-media (">=md") {
      .base {
        flex-wrap: nowrap;
      }
      .footer {
        flex-grow: 0;
      }
    }
  }
  ```

I also used tailwind and it of course says:
```
 Nested CSS was detected, but CSS nesting has not been configured correctly.
@steklo24/store:dev-clean: Please enable a CSS nesting plugin *before* Tailwind in your configuration.
```

My postcss config part looks like
```ts
     'postcss-import': {},
    'postcss-preset-mantine': {},
    'postcss-nested': {},
    'tailwindcss/nesting': 'postcss-nested',
    'postcss-include-media': {
      breakpoints,
    },
```

- This code works correctly:

  ```css
  @include-media (">=md") {
    .nowrapBreakpoint_md {
      .base {
        flex-wrap: nowrap;
      }
      .footer {
        flex-grow: 0;
      }
    }
  }
  ```

Question is: am I missing something?
